/**
 * Email utility — Brevo (Sendinblue) Transactional Email API
 *
 * Sends emails via the Brevo REST API instead of Nodemailer/Gmail SMTP.
 * Requires BREVO_API_KEY and BREVO_SENDER_EMAIL in .env
 */

const BREVO_API_URL = "https://api.brevo.com/v3/smtp/email";

function getConfig() {
  const apiKey = process.env.BREVO_API_KEY;
  const senderEmail = process.env.BREVO_SENDER_EMAIL || "noreply@taskmanager.com";
  const senderName = process.env.BREVO_SENDER_NAME || "Task Manager";

  if (!apiKey) {
    throw new Error(
      "Brevo API key not configured. Please set BREVO_API_KEY in your .env file."
    );
  }

  return { apiKey, senderEmail, senderName };
}

/**
 * Low-level helper: send a transactional email via Brevo API
 */
async function brevoSend({ to, subject, htmlContent }) {
  const { apiKey, senderEmail, senderName } = getConfig();

  const response = await fetch(BREVO_API_URL, {
    method: "POST",
    headers: {
      accept: "application/json",
      "content-type": "application/json",
      "api-key": apiKey,
    },
    body: JSON.stringify({
      sender: { name: senderName, email: senderEmail },
      to: [{ email: to }],
      subject,
      htmlContent,
    }),
  });

  if (!response.ok) {
    const errorBody = await response.text();
    throw new Error(
      `Brevo API error (${response.status}): ${errorBody}`
    );
  }

  return response.json();
}

// ─── Public API (same signatures as before) ────────────────────────────

async function sendDailyPlanEmail(to, schedule) {
  const scheduleHtml = schedule
    .map((item) => {
      const parts = item.split("→");
      if (parts.length === 2) {
        return `<div style="display:flex;align-items:center;gap:12px;padding:10px 16px;margin-bottom:8px;background:#1e1e2e;border-radius:10px;border-left:3px solid #8b5cf6;">
          <span style="color:#a78bfa;font-size:12px;font-weight:600;min-width:110px;font-family:monospace;">${parts[0].trim()}</span>
          <span style="color:#e2e8f0;font-weight:500;">→ ${parts[1].trim()}</span>
        </div>`;
      }
      return `<div style="padding:8px 16px;margin-bottom:6px;background:#1e1e2e;border-radius:8px;color:#e2e8f0;">${item}</div>`;
    })
    .join("");

  await brevoSend({
    to,
    subject: "Your Daily Plan",
    htmlContent: `
      <div style="font-family:'Segoe UI',sans-serif;max-width:600px;margin:0 auto;background:#0f0f1a;padding:32px;border-radius:16px;border:1px solid #2d2d3d;">
        <h1 style="font-size:24px;font-weight:700;background:linear-gradient(90deg,#8b5cf6,#3b82f6);-webkit-background-clip:text;-webkit-text-fill-color:transparent;margin:0 0 8px 0;">Your Daily Plan</h1>
        <p style="color:#6b7280;font-size:14px;margin:0 0 24px 0;">${new Date().toLocaleDateString(
          "en-IN",
          { dateStyle: "full" }
        )}</p>
        ${scheduleHtml}
        <p style="color:#4b5563;font-size:12px;margin-top:24px;">Generated by Task Manager — Stay focused and productive!</p>
      </div>
    `,
  });
}

async function sendNotificationEmail(to, deadlineSoon, overdue, upcoming = []) {
  const deadlineSoonHtml =
    deadlineSoon.length > 0
      ? `<h2 style="color:#f59e0b;font-size:16px;font-weight:700;margin:24px 0 10px 0;">Deadline Soon (Within 2 Days)</h2>` +
        deadlineSoon
          .map(
            (t) =>
              `<div style="padding:10px 16px;margin-bottom:8px;background:#1e1e2e;border-radius:10px;border-left:3px solid #f59e0b;"><span style="color:#fbbf24;font-weight:600;">${
                t.title
              }</span><br><small style="color:#6b7280;">Due: ${new Date(
                t.deadline
              ).toLocaleDateString("en-IN")}</small></div>`
          )
          .join("")
      : "";

  const overdueHtml =
    overdue.length > 0
      ? `<h2 style="color:#ef4444;font-size:16px;font-weight:700;margin:24px 0 10px 0;">Overdue Tasks</h2>` +
        overdue
          .map(
            (t) =>
              `<div style="padding:10px 16px;margin-bottom:8px;background:#1e1e2e;border-radius:10px;border-left:3px solid #ef4444;"><span style="color:#f87171;font-weight:600;">${
                t.title
              }</span><br><small style="color:#6b7280;">Was due: ${new Date(
                t.deadline
              ).toLocaleDateString("en-IN")}</small></div>`
          )
          .join("")
      : "";

  const upcomingHtml =
    upcoming.length > 0
      ? `<h2 style="color:#8b5cf6;font-size:16px;font-weight:700;margin:24px 0 10px 0;">Upcoming Tasks</h2>` +
        upcoming
          .map(
            (t) =>
              `<div style="padding:10px 16px;margin-bottom:8px;background:#1e1e2e;border-radius:10px;border-left:3px solid #8b5cf6;"><span style="color:#a78bfa;font-weight:600;">${
                t.title
              }</span><br><small style="color:#6b7280;">Due: ${new Date(
                t.deadline
              ).toLocaleDateString("en-IN")}</small></div>`
          )
          .join("")
      : "";

  if (!deadlineSoonHtml && !overdueHtml && !upcomingHtml) return null;

  const totalCount = deadlineSoon.length + overdue.length + upcoming.length;

  await brevoSend({
    to,
    subject: `Task Manager — ${totalCount} Pending Task${totalCount > 1 ? "s" : ""} Need Your Attention`,
    htmlContent: `
      <div style="font-family:'Segoe UI',sans-serif;max-width:600px;margin:0 auto;background:#0f0f1a;padding:32px;border-radius:16px;border:1px solid #2d2d3d;">
        <h1 style="font-size:22px;font-weight:700;color:#e2e8f0;margin:0 0 6px 0;">Task Notifications</h1>
        <p style="color:#6b7280;font-size:14px;margin:0 0 16px 0;">${new Date().toLocaleDateString(
          "en-IN",
          { dateStyle: "full" }
        )}</p>
        <p style="color:#94a3b8;font-size:13px;margin:0 0 16px 0;padding:8px 12px;background:#1e293b;border-radius:8px;">
          Summary: ${overdue.length} overdue | ${deadlineSoon.length} due soon | ${upcoming.length} upcoming
        </p>
        ${overdueHtml}
        ${deadlineSoonHtml}
        ${upcomingHtml}
        <p style="color:#4b5563;font-size:12px;margin-top:24px;">Stay on top of your tasks — Task Manager</p>
      </div>
    `,
  });

  return true;
}

module.exports = { sendDailyPlanEmail, sendNotificationEmail };
