import nodemailer from "nodemailer";

// Gmail SMTP transporter — works with any recipient email
function createTransporter() {
  const user = process.env.GMAIL_USER;
  const pass = process.env.GMAIL_APP_PASSWORD;

  if (!user || !pass || pass === "PASTE_YOUR_PASSWORD_HERE") {
    throw new Error("Gmail credentials not configured. Please set GMAIL_USER and GMAIL_APP_PASSWORD in your .env file.");
  }

  return nodemailer.createTransport({
    service: "gmail",
    auth: { user, pass },
  });
}

const FROM_NAME = `"Task Manager" <${process.env.GMAIL_USER}>`;

export async function sendDailyPlanEmail(to: string, schedule: string[]) {
  const scheduleHtml = schedule
    .map(item => {
      const parts = item.split("→");
      if (parts.length === 2) {
        return `<div style="display:flex;align-items:center;gap:12px;padding:10px 16px;margin-bottom:8px;background:#1e1e2e;border-radius:10px;border-left:3px solid #8b5cf6;">
          <span style="color:#a78bfa;font-size:12px;font-weight:600;min-width:110px;font-family:monospace;">${parts[0].trim()}</span>
          <span style="color:#e2e8f0;font-weight:500;">→ ${parts[1].trim()}</span>
        </div>`;
      }
      return `<div style="padding:8px 16px;margin-bottom:6px;background:#1e1e2e;border-radius:8px;color:#e2e8f0;">${item}</div>`;
    })
    .join("");

  await createTransporter().sendMail({
    from: FROM_NAME,
    to,
    subject: "✨ Your AI Daily Plan",
    html: `
      <div style="font-family:'Segoe UI',sans-serif;max-width:600px;margin:0 auto;background:#0f0f1a;padding:32px;border-radius:16px;border:1px solid #2d2d3d;">
        <h1 style="font-size:24px;font-weight:700;background:linear-gradient(90deg,#8b5cf6,#3b82f6);-webkit-background-clip:text;-webkit-text-fill-color:transparent;margin:0 0 8px 0;">✨ Your AI Daily Plan</h1>
        <p style="color:#6b7280;font-size:14px;margin:0 0 24px 0;">${new Date().toLocaleDateString("en-IN", { dateStyle: "full" })}</p>
        ${scheduleHtml}
        <p style="color:#4b5563;font-size:12px;margin-top:24px;">Generated by Task Manager AI — Stay focused and productive!</p>
      </div>
    `,
  });
}

export async function sendNotificationEmail(
  to: string,
  deadlineSoon: Array<{ title: string; deadline: Date }>,
  overdue: Array<{ title: string; deadline: Date }>
) {
  const deadlineSoonHtml = deadlineSoon.length > 0
    ? `<h2 style="color:#f59e0b;font-size:16px;font-weight:700;margin:24px 0 10px 0;">⏰ Deadline Soon</h2>` +
      deadlineSoon.map(t => `<div style="padding:10px 16px;margin-bottom:8px;background:#1e1e2e;border-radius:10px;border-left:3px solid #f59e0b;"><span style="color:#fbbf24;font-weight:600;">${t.title}</span><br><small style="color:#6b7280;">Due: ${new Date(t.deadline).toLocaleDateString("en-IN")}</small></div>`).join("")
    : "";

  const overdueHtml = overdue.length > 0
    ? `<h2 style="color:#ef4444;font-size:16px;font-weight:700;margin:24px 0 10px 0;">🚨 Overdue Tasks</h2>` +
      overdue.map(t => `<div style="padding:10px 16px;margin-bottom:8px;background:#1e1e2e;border-radius:10px;border-left:3px solid #ef4444;"><span style="color:#f87171;font-weight:600;">${t.title}</span><br><small style="color:#6b7280;">Was due: ${new Date(t.deadline).toLocaleDateString("en-IN")}</small></div>`).join("")
    : "";

  if (!deadlineSoonHtml && !overdueHtml) return null;

  await createTransporter().sendMail({
    from: FROM_NAME,
    to,
    subject: "🔔 Task Manager — Notification Summary",
    html: `
      <div style="font-family:'Segoe UI',sans-serif;max-width:600px;margin:0 auto;background:#0f0f1a;padding:32px;border-radius:16px;border:1px solid #2d2d3d;">
        <h1 style="font-size:22px;font-weight:700;color:#e2e8f0;margin:0 0 6px 0;">🔔 Task Notifications</h1>
        <p style="color:#6b7280;font-size:14px;margin:0 0 16px 0;">${new Date().toLocaleDateString("en-IN", { dateStyle: "full" })}</p>
        ${deadlineSoonHtml}
        ${overdueHtml}
        <p style="color:#4b5563;font-size:12px;margin-top:24px;">Stay on top of your tasks — Task Manager AI</p>
      </div>
    `,
  });

  return true;
}
